# Generated by Django 4.2.3 on 2023-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_validation_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validation_info',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
