# Generated by Django 4.2.3 on 2023-07-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_validation_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='validation_info',
        ),
    ]
