# Generated by Django 4.2.3 on 2023-07-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_user_validation_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_info',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
