# Generated by Django 4.2.3 on 2023-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_validation_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
