# Generated by Django 4.2.3 on 2023-08-14 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_user_token_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='validation_info',
        ),
        migrations.AddField(
            model_name='user',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='validation_or_reset_tokens',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 1, 51, 51, 566220, tzinfo=datetime.timezone.utc)),
        ),
    ]
