# Generated by Django 4.2.3 on 2023-08-18 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_user_validation_info_user_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 19, 20, 45, 434206, tzinfo=datetime.timezone.utc)),
        ),
    ]
