# Generated by Django 4.2.3 on 2023-08-19 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_user_token_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 3, 12, 21, 169199, tzinfo=datetime.timezone.utc)),
        ),
    ]
