# Generated by Django 4.2.3 on 2023-08-19 14:36

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_user_token_timestamp_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='bro', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 14, 36, 5, 281506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
