# Generated by Django 4.2.3 on 2023-08-19 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_user_alias_alter_user_token_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 14, 36, 45, 525558, tzinfo=datetime.timezone.utc)),
        ),
    ]
