# Generated by Django 4.2.3 on 2023-08-20 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_user_token_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 4, 22, 28, 311104, tzinfo=datetime.timezone.utc)),
        ),
    ]
