# Generated by Django 4.2.3 on 2023-09-04 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_remove_user_alias_alter_user_token_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 18, 2, 17, 646511, tzinfo=datetime.timezone.utc)),
        ),
    ]
