# Generated by Django 4.2.3 on 2023-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='footnote1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='footnote2',
            field=models.URLField(null=True),
        ),
    ]
