# Generated by Django 4.2.3 on 2023-08-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_post_footnote1_post_footnote2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explanation1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='explanation2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='footnote1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='footnote2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
