# Generated by Django 4.2.3 on 2023-09-04 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flag_app', '0002_rename_harmful_flag_explicit_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
